### ISSUE TITLE
get error when import cardio in Anaconda python 3.6.3

### ISSUE THREAD

**Issue by tuhuynh** [analysiscenter/cardio#7]
>>> import cardio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\HTTU\Anaconda3\lib\site-packages\cardio\__init__.py", line 3, in <module>
    from . import dataset  # pylint: disable=wildcard-import
  File "C:\Users\HTTU\Anaconda3\lib\site-packages\cardio\dataset\__init__.py", line 4, in <module>
    sys.modules[__package__] = importlib.import_module('.dataset', __package__)
  File "C:\Users\HTTU\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\HTTU\Anaconda3\lib\site-packages\cardio\dataset\dataset\__init__.py", line 9, in <module>
    from .batch import Batch, ArrayBatch, DataFrameBatch
  File "C:\Users\HTTU\Anaconda3\lib\site-packages\cardio\dataset\dataset\batch.py", line 21, in <module>
    import dask.dataframe as dd
  File "C:\Users\HTTU\Anaconda3\lib\site-packages\dask\dataframe\__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "C:\Users\HTTU\Anaconda3\lib\site-packages\dask\dataframe\core.py", line 40, in <module>
    pd.core.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas.core.computation' has no attribute 'expressions'

**Comment by roman-kh** [comment]
It looks like you need to update `dask` package to a newer version as the installed one is incompatible with the installed version of `pandas`.

**Comment by tuhuynh** [comment]
Yeah,IT worked. Thanks roman-kh alot.
